### PR TITLE
added conversion of Nullable<> values

### PR DESCRIPTION
**Pull request by dittodhole**

### CODE REVIEW

**Comment by dittodhole** [comment]
> SharpConfig.SettingValueCastException: Failed to convert value '' to type System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].
>    at SharpConfig.Setting.ConvertValue(String value, Type type)
>    at SharpConfig.Setting.GetValueTyped(Type type)

**Comment by cemdervis** [comment]
What is the purpose of supporting Nullable?

**Comment by dittodhole** [comment]
We have followig .ini-file:

```
[SECTION]
Key=
```

Following call fails with an exception (posted above):
```
var configuration = Configuration.LoadFromFile("foo.ini");
var section = configuration["SECTION];
var setting = section["Key"];
var value = setting.GetValueTyped(typeof (int?));
```

**Comment by cemdervis** [comment]
Seems because there is not null/empty check for the string value in ConvertValue().
Was Nullable supposed to prevent this, in this case?

**Comment by dittodhole** [comment]
I have done this by adding a fallback for `null` values if the type is a descendant of `Nullable<>` only :smile:

I expect that the previously mentioned reading of the setting does not throw an exception, but rather just returns `null`.

**Comment by cemdervis** [comment]
Oh I see. We could prevent exceptions altogether, atleast in GetValueTyped<T>().
We could check if the value is null/empty, and return [default(T)](http://msdn.microsoft.com/en-us/library/xwth0h0d.aspx) in that case, which resolves to null for reference types, and default-constructed value for value types.
I don't know of any equivalent for non-generic types, so implementing this in GetValueTyped(Type) would be another challenge I guess. If there's no equivalent, we could leave GetValueTyped(Type) unchanged and throw if the value is null. What do you think?

**Comment by dittodhole** [comment]
I am not struggling with exceptions per se - just in this very case ...

I would still like to see the descendant check for nullable types in `ConvertValue`, because there is some logic for other value types (like bool), which is also applied for `bool?` after my PR.

**Comment by cemdervis** [comment]
I think I see the problem. You want to be able to get a null reference instead of 0 if the key in the file is empty, right?

**Comment by dittodhole** [comment]
> You want to be able to get a null reference instead of 0 if the key in the file is empty, right?

Nope, I want a `null` if the provided type is a descendant of `Nullable<>`.

**Comment by cemdervis** [comment]
Oops, alright, this line in the changes confused me:
```csharp
return ConvertValue(value, underlyingType);
```

Would be better off by just overwriting the parameter:
```csharp
type = underlyingType;
```

Now I got it, and seems like another good addition to SharpConfig. Thank you!

**Comment by dittodhole** [comment]
true that :+1:

should have rather replaced the variable instead of making it recursive - but who knows ... `Nullable<Nullable<int>>` is a valid type :cry:

**Comment by cemdervis** [comment]
Are you sure that it's a valid type? I thought Nullable is invalid as a generic parameter, but who knows.. :smiley:

**Comment by dittodhole** [comment]
public struct Nullable<T> where T : struct

So, `T` must be a `struct`, which `Nullable<>` is ...
But if I try to do something like `Nullable<Nullable<int>>` the compiler gives me

> The type 'int`?' must be a non-nullable value type in order to use it as a paramter 'T' in the generic type or method 'Nullable<T>'

So, I was totally wrong with multiple "unfolding" - corrected my PR - thanks for pointing that out!

**Comment by cemdervis** [comment]
The C# compiler seems to have a special rule for Nullable, which is to also recognize it as a "type that behaves like a reference". That was a new one for me to be honest.

**Comment by dittodhole** [comment]
yeah, looks like a special treatment of those `Nullable<>` :+1:

**Pull request merged**
